// Generated by @openapi-codegen

export const xataColumnTypes = [
  "bool",
  "int",
  "float",
  "string",
  "text",
  "email",
  "multiple",
  "link",
  "object",
  "datetime",
  // "vector", // Need special UX
  // "file[]", // Not supported yet
  // "file",   // Not supported yet
] as const;
