/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
import type * as Schemas from "./xataSchemas";

/**
 * @example {"message":"invalid API key"}
 */
export type AuthError = {
  id?: string;
  message: string;
};

export type BadRequestError = {
  id?: string;
  message: string;
};

export type BranchMigrationPlan = {
  version: number;
  migration: Schemas.BranchMigration;
};

export type BulkError = {
  errors: {
    message?: string;
    status?: number;
  }[];
};

export type BulkInsertResponse =
  | {
      recordIDs: string[];
    }
  | {
      records: Schemas.Record[];
    };

/**
 * @example {"migrationID":"mig_c7m19ilcefoebpqj12p0"}
 */
export type MigrationIdResponse = {
  /*
   * @minLength 1
   */
  migrationID: string;
};

export type QueryResponse = {
  records: Schemas.Record[];
  meta: Schemas.RecordsMetadata;
};

export type RecordResponse = Schemas.Record;

export type RecordUpdateResponse =
  | Schemas.Record
  | {
      id: string;
      xata: {
        version: number;
      };
    };

export type SearchResponse = {
  records: Schemas.Record[];
};

export type SimpleError = {
  id?: string;
  message: string;
};
