// Generated by @openapi-codegen

import { Column } from "./xataSchemas";

export const xataColumnTypes: Column["type"][] = [
  "bool",
  "int",
  "float",
  "string",
  "text",
  "email",
  "multiple",
  "link",
  "object",
];
